import Foundation
import HealthKit

// MARK: - 探针结果类型

/// 采样密度探针：最近 N 小时里**到底有多少条、间隔多密**。
///
/// 这是回答「S12 宣称的全天每 5 秒一次心率，到底有没有进 HealthKit」的唯一办法
/// —— 只有直接问 HealthKit，不能看我们自己的库（我们库里本来就只有同步过的）。
struct CadenceProbe: Sendable {
    let hours: Int
    let sampleCount: Int
    /// 相邻样本时间戳差值的中位数（秒）。5 秒采样的话这里应该接近 5。
    let medianGap: TimeInterval?
    let minGap: TimeInterval?
    let maxGap: TimeInterval?
    let latest: Date?
}

/// HRV (RMSSD) 探针。
///
/// ⚠️ 关键的未知数：Apple **从未确认** Apple Watch 会往 `heartRateVariabilityRMSSD` 写数据。
/// 这个类型是 iOS/watchOS 27 新加的，文档只有符号声明、没有 Discussion。
/// `typeAvailable == true && sampleCount == 0` 的含义是「类型在、但设备没写」。
struct RmssdProbe: Sendable {
    let typeAvailable: Bool
    let sampleCount: Int
    let latest: Date?
}

/// 某一天的序列条数。
struct DailySeriesCount: Sendable {
    let day: Date
    let count: Int
}

/// 最新一条序列的**逐拍检查**（只跑一条，用户手动触发诊断时才跑）。
///
/// ⚠️ 这里**没有任何解释性计算**：只有拍数、时长、洞、顺序 ——
/// 全部是**样本自身的属性**（"这条数据完整吗"），不是对信号的解释。
/// RR 间期 / SDNN / Poincaré / PSD 一律在手机上算，手表界面也不显示它们
/// （需求方定的边界，自检脚本第 16 节守着）。
///
/// 为什么值得单独跑这一条查询：`precededByGap` 只能从逐拍回调里拿到，
/// 而它决定了"手机端要不要丢掉某些跨洞的间隔"。它的真实分布（有没有、多不多）
/// 直接决定那套跨洞过滤是"必需"还是"几乎不触发"。
struct BeatDetail: Sendable {
    /// 逐拍回调**实际**收到的拍数
    let reportedBeats: Int
    /// 样本自报的 `HKSeriesSample.count`
    ///
    /// 拿它和 `reportedBeats` 对照，就能知道 `count` 这个属性可不可信 ——
    /// 可信的话以后核对拍数就不必再跑一次昂贵的逐拍查询。
    let declaredBeats: Int
    /// 第一拍的 `precededByGap`（Apple 没说它一定是什么值，所以如实报出来）
    let firstBeatPrecededByGap: Bool?
    /// **第一拍之外**有多少拍被标了"前面有洞"
    let innerGapCount: Int
    /// 首拍到末拍的跨度（秒）—— 和 `endDate - startDate` 对照可交叉验证
    let spanSeconds: TimeInterval?
    /// 回调是否**严格升序**
    ///
    /// 我们算 RR 靠的是相邻相减，所以顺序是**隐含前提**；
    /// 而 Apple 的文档只说"每一拍调用一次"，**从没保证过顺序**。
    /// 这个字段就是去把这个前提验证掉。
    let isAscending: Bool
}

/// 心跳序列（RR 间期）探针。
///
/// ## 📌 上一版这里写着"预期结果是 seriesCount == 0"，那句话**是错的**
/// 原文断言"Apple 官方文档从未说过手表会自动产生它（`HKHeartbeatSeriesSample`）"。
/// 实际上官方文档里有一句正面回答，在 `HKMetadataKeyAlgorithmVersion` 的 Note 里：
///
/// > "In watchOS 8, the system uses this key for **heartRateVariabilitySDNN** and
/// > **HKHeartbeatSeriesSample** samples **generated by Apple Watch**."
/// > —— <https://developer.apple.com/documentation/healthkit/hkmetadatakeyalgorithmversion>
///
/// 也就是说：**系统会生成心跳序列样本**，而且它们**带算法版本元数据**。
/// 这句话只证明了"存在"，仍然**没有**说明频率、时长和触发条件 ——
/// 而那正是下面这些字段要去量的东西。
///
/// 顺带得到一个现成的判据：`seriesWithAlgorithmVersion` 能直接告诉我们
/// "这些序列是不是系统产的"（第三方 app 用 `HKHeartbeatSeriesBuilder` 写的那些
/// 不会带这个键）。
struct HeartbeatSeriesProbe: Sendable {
    let days: Int
    let seriesCount: Int
    let latestSampleDate: Date?
    /// **最早**一条序列的时间。
    ///
    /// 这个字段是为了回答一个具体的因果问题：「现在能看到数据了，
    /// 是因为补了读权限，还是因为打开了房颤历史？」
    ///
    /// 判据：**读权限只影响"我们能不能看见"，不影响手表写不写。**
    /// 所以只要最早那条**早于**用户打开房颤历史的时间，就说明手表一直在写，
    /// 之前看不到纯粹是没权限。
    let earliestSampleDate: Date?
    /// 近 N 天**每天**的序列条数（旧 → 新，没有数据的日子补 0）。
    ///
    /// 为什么不只给"最早/最新"：只给两端的话，看不出中间是"一直是 0 然后某天突然开始"，
    /// 还是"稀稀拉拉一直有"。**这个分布才是判定的直接证据** ——
    /// 数据只从某天开始有 = 那天开了某个开关。
    let dailyCounts: [DailySeriesCount]

    // ——— 以下回答「多久一条 / 一条多长 / 一条几拍」，全部无需逐拍查询 ———

    /// 相邻两条序列**起点**间隔（秒）的中位 / 最小 / 最大。
    ///
    /// ⚠️ 这正是"到底几分钟一条"的答案来源。**不要靠盯着诊断页等** ——
    /// 序列的产生是条件驱动的（睡眠/静息），白天的十几分钟空档
    /// 完全不能推出"平均节奏不是 4 分钟"。要看分布，不要看某一次。
    let medianInterval: TimeInterval?
    let minInterval: TimeInterval?
    let maxInterval: TimeInterval?

    /// 单条序列时长的中位 / 最小 / 最大（秒，来自 `endDate - startDate`）。
    let medianDuration: TimeInterval?
    let minDuration: TimeInterval?
    let maxDuration: TimeInterval?

    /// 单条序列拍数的中位 / 最小 / 最大。
    ///
    /// 用 `HKSeriesSample.count` —— 这个属性是**免费**的，不需要逐拍查询。
    /// 它到底可不可信，由 `latestBeatDetail` 里的 declared/reported 对照来回答。
    let medianBeatCount: Double?
    let minBeatCount: Int?
    let maxBeatCount: Int?

    /// 按**本地小时**分桶的条数（24 个，0 点 → 23 点）。
    ///
    /// 回答的是"是不是只在夜里"。和 `dailyCounts` 是不同粒度：
    /// 那个看"哪一天开始有"，这个看"一天里的哪个时段有"。
    let hourlyCounts: [Int]

    /// 最新一条的逐拍检查结果（见 `BeatDetail`）。
    let latestBeatDetail: BeatDetail?

    /// 最近一条序列的 `HKMetadataKeyAlgorithmVersion`（系统写入的算法版本）。
    let algorithmVersion: String?

    /// 近 N 天里**带算法版本键**的序列条数。
    ///
    /// 判据：系统（Apple Watch）产的那些带这个键，第三方 app 写的不带。
    /// 所以"这个数字 ≈ seriesCount"就说明数据是系统产的，而不是某个 app 写进来的。
    let seriesWithAlgorithmVersion: Int

    /// ⚠️ 这里仍然**刻意没有** RR 间期 / HRV / 中位 RR 这些字段。
    ///
    /// 手表的职责是"搬运"，不是"解释"：RR 间期、Poincaré、SDNN（以后还有 PSD）
    /// **全部在手机上算**。手表代码的迭代成本极高（要走 watchOS 发布 + 用户装表），
    /// 手机随时能更新 —— 所以任何解释性计算都不该出现在手表上。
    ///
    /// 上面那些字段能出现在这里，是因为它们回答的是
    /// 「**HealthKit 里有没有、有多少、什么时候的、完不完整**」，
    /// 而不是"这些心跳意味着什么"。
}

/// HealthKit 侧的全部探针结果
struct HealthKitProbeReport: Sendable {
    let catalogMetricCount: Int
    let heartRate: CadenceProbe?
    let rmssd: RmssdProbe
    let heartbeat: HeartbeatSeriesProbe
    /// 单个探针失败时记下来，不影响其它探针（不追求完整性原则）
    let errors: [String]
}

// MARK: - 探针本体

/// 直接向 HealthKit 提问的探针集合。
///
/// 与 `HealthSyncEngine` 的区别：同步引擎关心「把增量搬进本地库」，
/// 探针关心「**HealthKit 里究竟有什么**」。两者不能互相替代 ——
/// 本地库里是 0，可能是没授权、可能是同步没跑、也可能是设备根本没这个数据，
/// 只有直接问 HealthKit 才能把「类型不存在」和「类型存在但没数据」区分开。
actor HealthProbe {

    static let shared = HealthProbe()

    private let store = HKHealthStore()

    // MARK: 对外入口

    /// 跑齐所有探针。任何一个失败都不影响其它（符合「不追求完整性」原则）。
    func runAll(heartRateHours: Int, days: Int) async -> HealthKitProbeReport {
        var errors: [String] = []

        let heartRate = await heartRateCadence(hours: heartRateHours)
        if heartRate == nil { errors.append("心率密度探针失败（类型拿不到）") }

        let rmssd = await rmssdProbe(days: days)

        let heartbeat = await heartbeatSeries(days: days)

        return HealthKitProbeReport(
            catalogMetricCount: MetricCatalog.all.count,
            heartRate: heartRate,
            rmssd: rmssd,
            heartbeat: heartbeat,
            errors: errors
        )
    }

    // MARK: 心率密度

    /// 最近 N 小时的心率样本数与间隔分布。
    ///
    /// 取回样本再自己算间隔，而不是用统计查询 —— 因为我们要的恰恰是
    /// **间隔的分布**（中位数），这只能从原始时间戳算。
    /// 6 小时最坏 4320 条，一次性查询在手表上可以接受（这是手动触发的诊断，不是后台任务）。
    func heartRateCadence(hours: Int) async -> CadenceProbe? {
        guard let type = HKQuantityType.quantityType(forIdentifier: .heartRate) else { return nil }
        let from = Date().addingTimeInterval(-Double(hours) * 3600)
        let predicate = HKQuery.predicateForSamples(withStart: from, end: nil, options: .strictStartDate)
        let samples = await fetch(type: type, predicate: predicate, limit: 20_000, ascending: true)

        let sorted = samples.map(\.startDate).sorted()
        var gaps: [TimeInterval] = []
        if sorted.count >= 2 {
            for i in 1..<sorted.count {
                gaps.append(sorted[i].timeIntervalSince(sorted[i - 1]))
            }
        }
        return CadenceProbe(hours: hours,
                            sampleCount: sorted.count,
                            medianGap: Self.median(gaps),
                            minGap: gaps.min(),
                            maxGap: gaps.max(),
                            latest: sorted.last)
    }

    // MARK: RMSSD

    func rmssdProbe(days: Int) async -> RmssdProbe {
        // 用 MetricCatalog 里那个「原始字符串构造」的标识符 —— 这是全 app 唯一的来源，
        // 避免两处字符串写得不一致。
        guard let type = HKQuantityType.quantityType(forIdentifier: MetricCatalog.rmssdIdentifier) else {
            return RmssdProbe(typeAvailable: false, sampleCount: 0, latest: nil)
        }
        let from = Date().addingTimeInterval(-Double(days) * 86400)
        let predicate = HKQuery.predicateForSamples(withStart: from, end: nil, options: .strictStartDate)
        let samples = await fetch(type: type, predicate: predicate, limit: HKObjectQueryNoLimit, ascending: false)
        return RmssdProbe(typeAvailable: true,
                          sampleCount: samples.count,
                          latest: samples.first?.startDate)
    }

    // MARK: 心跳序列（RR 间期）

    func heartbeatSeries(days: Int) async -> HeartbeatSeriesProbe {
        // ⚠️ 用 `MetricCatalog.heartbeatSeriesType` 而不是就地 `HKSeriesType.heartbeat()`：
        //    这个类型**同时**是"读授权的类型"和"要查的类型"，
        //    两处各写一遍就可能出现「申请了 A、查的是 B」——而那种情况下查询返回空数组，
        //    表现成"设备没数据"，完全看不出来。
        let type = MetricCatalog.heartbeatSeriesType
        let from = Date().addingTimeInterval(-Double(days) * 86400)
        let predicate = HKQuery.predicateForSamples(withStart: from, end: nil, options: .strictStartDate)
        // ⚠️ 按**升序**取。以前是降序（那时只要"最新一条"），
        //    而间隔分布、小时分桶、"最新一条"三者都要求时间有序 ——
        //    降序取回来再自己排一次是没必要的来回。
        let samples = await fetch(type: type, predicate: predicate, limit: HKObjectQueryNoLimit, ascending: true)

        let starts = samples.map(\.startDate)
        let durations = samples.map { $0.endDate.timeIntervalSince($0.startDate) }

        // `HKSeriesSample.count` 是**免费**的（不需要逐拍查询）。
        // 0 是异常值，排除掉，别让它把中位数带偏。
        let beatCounts = samples.compactMap { ($0 as? HKSeriesSample)?.count }.filter { $0 > 0 }

        var intervals: [TimeInterval] = []
        if starts.count >= 2 {
            for index in 1..<starts.count {
                intervals.append(starts[index].timeIntervalSince(starts[index - 1]))
            }
        }

        // 「这些序列是不是系统产的」—— 系统写的带算法版本键，第三方 app 写的不带
        let withVersion = samples.filter { $0.metadata?[HKMetadataKeyAlgorithmVersion] != nil }
        let latest = samples.last
        let version = latest?.metadata?[HKMetadataKeyAlgorithmVersion].map { String(describing: $0) }

        // 逐拍检查**只跑最新这一条**。
        // 为什么在探针里跑逐拍查询是合理的（而同步引擎里必须限量）：
        // 探针只在用户手动点「重新探测」时跑，是前台的一次性动作；
        // 同步引擎跑在后台那几秒里，那里每轮最多展开 6 条。
        // 而且这里**不算 RR** —— 只看有几拍、有没有洞、顺序对不对。
        var detail: BeatDetail?
        if let series = latest as? HKHeartbeatSeriesSample {
            detail = await beatDetail(of: series)
        }

        return HeartbeatSeriesProbe(days: days,
                                    seriesCount: samples.count,
                                    latestSampleDate: latest?.startDate,
                                    earliestSampleDate: starts.first,
                                    dailyCounts: Self.dailyCounts(dates: starts, days: days),
                                    medianInterval: Self.median(intervals),
                                    minInterval: intervals.min(),
                                    maxInterval: intervals.max(),
                                    medianDuration: Self.median(durations),
                                    minDuration: durations.min(),
                                    maxDuration: durations.max(),
                                    medianBeatCount: Self.median(beatCounts.map { Double($0) }),
                                    minBeatCount: beatCounts.min(),
                                    maxBeatCount: beatCounts.max(),
                                    hourlyCounts: Self.hourlyCounts(dates: starts),
                                    latestBeatDetail: detail,
                                    algorithmVersion: version,
                                    seriesWithAlgorithmVersion: withVersion.count)
    }

    /// 查**一条**序列的逐拍数据，只回答"样本自身完不完整"。
    ///
    /// 失败就返回 `nil`（不追求完整性原则）—— 诊断页会据此显示"没查到"，
    /// 而不是显示一个编造出来的 0。
    private func beatDetail(of sample: HKHeartbeatSeriesSample) async -> BeatDetail? {
        let declared = (sample as HKSeriesSample).count
        do {
            let beats = try await HeartbeatReader.beats(of: sample, store: store)
            let stamps = beats.stamps

            var ascending = true
            var innerGaps = 0
            if stamps.count >= 2 {
                for index in 1..<stamps.count {
                    // ⚠️ 顺序是**我们算 RR 的隐含前提**（相邻相减），
                    //    而 Apple 从没保证过顺序 —— 所以在这里把它验掉。
                    if stamps[index] < stamps[index - 1] { ascending = false }
                    // 第一拍没有"前一拍"，它身上的 precededByGap 不构成任何间期，所以从 1 数起。
                    if index < beats.gaps.count, beats.gaps[index] { innerGaps += 1 }
                }
            }

            var span: TimeInterval?
            if let first = stamps.first, let last = stamps.last, stamps.count >= 2 {
                span = last - first
            }

            return BeatDetail(reportedBeats: stamps.count,
                              declaredBeats: declared,
                              firstBeatPrecededByGap: beats.gaps.first,
                              innerGapCount: innerGaps,
                              spanSeconds: span,
                              isAscending: ascending)
        } catch {
            return nil
        }
    }

    /// 按**本地小时**分桶（24 个，0 点 → 23 点）。
    ///
    /// ⚠️ 和坑 #36 不冲突，别混：那里说的是**按天**分桶不能用 epoch 取模
    /// （会算成 UTC 午夜 → 东八区变成早上 8 点）。小时直接取
    /// `Calendar` 的 component 就对了 —— 理由正是"所有真实时区的偏移
    /// 都是 15 分钟的整数倍"，而小时的边界处处对齐。
    private static func hourlyCounts(dates: [Date]) -> [Int] {
        let calendar = Calendar.current
        var buckets = [Int](repeating: 0, count: 24)
        for date in dates {
            let hour = calendar.component(.hour, from: date)
            if hour >= 0 && hour < 24 { buckets[hour] += 1 }
        }
        return buckets
    }

    /// 按**本地自然日**分桶，没有数据的日子**补 0**。
    ///
    /// ⚠️ 补 0 是关键：只列"有数据的那几天"会跳过"哪几天是空的"，
    /// 而那恰恰是判断"某天打开了某个开关"的依据。
    /// 用 `Calendar.startOfDay` 而不是 epoch 取模 —— 后者算出来的是 UTC 午夜，
    /// 在东八区就成了早上 8 点（同一个坑在图表侧也踩过）。
    private static func dailyCounts(dates: [Date], days: Int) -> [DailySeriesCount] {
        let calendar = Calendar.current
        var buckets: [Date: Int] = [:]
        for date in dates {
            buckets[calendar.startOfDay(for: date), default: 0] += 1
        }

        let today = calendar.startOfDay(for: .now)
        var result: [DailySeriesCount] = []
        for offset in stride(from: days - 1, through: 0, by: -1) {
            guard let day = calendar.date(byAdding: .day, value: -offset, to: today) else { continue }
            result.append(DailySeriesCount(day: day, count: buckets[day] ?? 0))
        }
        return result
    }

    // MARK: 底层查询

    /// 一次性 `HKSampleQuery` 的 async 包装。
    private func fetch(type: HKSampleType,
                       predicate: NSPredicate?,
                       limit: Int,
                       ascending: Bool) async -> [HKSample] {
        await withCheckedContinuation { cont in
            let sort = [NSSortDescriptor(key: HKSampleSortIdentifierStartDate, ascending: ascending)]
            let query = HKSampleQuery(sampleType: type,
                                      predicate: predicate,
                                      limit: limit,
                                      sortDescriptors: sort) { _, samples, _ in
                // 没授权时这里返回的是空数组而不是错误 —— 所以「0 条」同时意味着
                // 「没数据」或「没授权」，界面上必须如实说明这一点。
                cont.resume(returning: samples ?? [])
            }
            store.execute(query)
        }
    }

    private static func median(_ xs: [Double]) -> Double? {
        guard !xs.isEmpty else { return nil }
        let sorted = xs.sorted()
        let mid = sorted.count / 2
        return sorted.count % 2 == 0 ? (sorted[mid - 1] + sorted[mid]) / 2 : sorted[mid]
    }
}
